languageCode = "en"
languageName = "English"
weight = 2
title = "Blowfish"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2006-01-02 15:04:05 Monday"
  logo = "img/blowfish_logo_transparent.png"
  description = "xxxxxxxxxxxxx"

[params.author]
  name = "Joe"
  image = "img/blowfish_logo.png"
  headline = "xxx languages params.author headline xxx"
  bio = "xxx languages params.author bio xxx"
  links = [
    { x-twitter = "https://twitter.com/burufugu" },
    { github = "https://github.com/nunocoracao/blowfish" },
  ]