languageCode = "zh-cn"
languageName = "简体中文"
weight = 1
title = "language配置中的title"

[params]
  displayName = "简体中文"
  isoCode = "zh-cn"
  rtl = false
  #dateFormat = "2006-01-02" #使用Hugo框架的时间格式组件创建日期字符串格式，例如：2006 代表 year组件，表示日期字符串的年部分
  #dateFormat = "2 January 2006"
  dateFormat = "2006-01-02 15:04:05 Monday"
  logo = "img/blowfish_logo_transparent.png"
  description = "一个强大、轻量级的 Hugo 主题。"

[params.author]
  name = "Joe"
  image = "img/blowfish_logo.png"
  headline = "一个强大、轻量级的 Hugo 主题。"
  bio = "一个强大、轻量级的 Hugo 主题。"
  links = [
    { x-twitter = "https://twitter.com/burufugu" },
    { github = "https://github.com/nunocoracao/blowfish" },
  ]